### ISSUE TITLE
Relocate License to root of project

### ISSUE THREAD

**Issue by Linesmerrill** [bhaveshgarg2000/Hacktober-DSA-2022#10]
I see in the [README](https://github.com/bhaveshgarg2000/Hacktober-DSA-2022/blob/master/README.md)  that you mention the [LICENSE](https://github.com/bhaveshgarg2000/Hacktober-DSA-2022/blob/master/LICENSE). It seems like you are considering applying this license, but GitHub currently doesn't recognize these references in your repository. To apply this license in a way that the community can recognize, you can add a file in the root directory of your default branch named LICENSE containing your license.

**Comment by df-bhavesh** [comment]
OK

**Comment by df-bhavesh** [comment]
@Linesmerrill You Can fix

**Comment by Linesmerrill** [comment]
Is there a specific license you would like to use? You can find information on various licenses [here](https://opensource.org/licenses). To choose the right license for your project, check out [choosealicense.com](https://choosealicense.com/). 

Once you pick out one you would like to use, I can open PR to add that to your project.

**Comment by df-bhavesh** [comment]
Do one thing add Dummy Template I'll add things in template.
Thanks & Regards
Bhavesh Krishan Garg
SDE

**Comment by Linesmerrill** [comment]
Ok, adding that now.

**Comment by Linesmerrill** [comment]
PR here: https://github.com/bhaveshgarg2000/Hacktober-DSA-2022/pull/11

**Comment by df-bhavesh** [comment]
I'm looking into it

**Comment by bhaveshgarg2000** [comment]
Hi @Linesmerrill I'm looking for Opportunity

**Comment by Linesmerrill** [comment]
Thanks for merging! 👍🏻

**Comment by bhaveshgarg2000** [comment]
Can we talk @Linesmerrill ?
